module IMS::LIS
  module Roles
    module Context
      module Handles
        Learner = "Learner"
        Learner_Learner = "Learner/Learner"
        Learner_NonCreditLearner = "Learner/NonCreditLearner"
        Learner_GuestLearner = "Learner/GuestLearner"
        Learner_ExternalLearner = "Learner/ExternalLearner"
        Learner_Instructor = "Learner/Instructor"
        Instructor = "Instructor"
        Instructor_PrimaryInstructor = "Instructor/PrimaryInstructor"
        Instructor_Lecturer = "Instructor/Lecturer"
        Instructor_GuestInstructor = "Instructor/GuestInstructor"
        Instructor_ExternalInstructor = "Instructor/ExternalInstructor"
        ContentDeveloper = "ContentDeveloper"
        ContentDeveloper_ContentDeveloper = "ContentDeveloper/ContentDeveloper"
        ContentDeveloper_Librarian = "ContentDeveloper/Librarian"
        ContentDeveloper_ContentExpert = "ContentDeveloper/ContentExpert"
        ContentDeveloper_ExternalContentExpert = "ContentDeveloper/ExternalContentExpert"
        Member = "Member"
        Member_Member = "Member/Member"
        Manager = "Manager"
        Manager_AreaManager = "Manager/AreaManager"
        Manager_CourseCoordinator = "Manager/CourseCoordinator"
        Manager_Observer = "Manager/Observer"
        Manager_ExternalObserver = "Manager/ExternalObserver"
        Mentor = "Mentor"
        Mentor_Mentor = "Mentor/Mentor"
        Mentor_Reviewer = "Mentor/Reviewer"
        Mentor_Advisor = "Mentor/Advisor"
        Mentor_Auditor = "Mentor/Auditor"
        Mentor_Tutor = "Mentor/Tutor"
        Mentor_LearningFacilitator = "Mentor/LearningFacilitator"
        Mentor_ExternalMentor = "Mentor/ExternalMentor"
        Mentor_ExternalReviewer = "Mentor/ExternalReviewer"
        Mentor_ExternalAdvisor = "Mentor/ExternalAdvisor"
        Mentor_ExternalAuditor = "Mentor/ExternalAuditor"
        Mentor_ExternalTutor = "Mentor/ExternalTutor"
        Mentor_ExternalLearningFacilitator = "Mentor/ExternalLearningFacilitator"
        Administrator = "Administrator"
        Administrator_Administrator = "Administrator/Administrator"
        Administrator_Support = "Administrator/Support"
        Administrator_Developer = "Administrator/Developer"
        Administrator_SystemAdministrator = "Administrator/SystemAdministrator"
        Administrator_ExternalSystemAdministrator = "Administrator/ExternalSystemAdministrator"
        Administrator_ExternalDeveloper = "Administrator/ExternalDeveloper"
        Administrator_ExternalSupport = "Administrator/ExternalSupport"
        TeachingAssistant = "TeachingAssistant"
        TeachingAssistant_TeachingAssistant = "TeachingAssistant/TeachingAssistant"
        TeachingAssistant_TeachingAssistantSection = "TeachingAssistant/TeachingAssistantSection"
        TeachingAssistant_TeachingAssistantSectionAssociation = "TeachingAssistant/TeachingAssistantSectionAssociation"
        TeachingAssistant_TeachingAssistantOffering = "TeachingAssistant/TeachingAssistantOffering"
        TeachingAssistant_TeachingAssistantTemplate = "TeachingAssistant/TeachingAssistantTemplate"
        TeachingAssistant_TeachingAssistantGroup = "TeachingAssistant/TeachingAssistantGroup"
        TeachingAssistant_Grader = "TeachingAssistant/Grader"
      end
    end
  end
end
