module IMS::LIS
  module Roles
    module Context
      module URNs
        Learner = "urn:lti:role:ims/lis/Learner"
        Learner_Learner = "urn:lti:role:ims/lis/Learner/Learner"
        Learner_NonCreditLearner = "urn:lti:role:ims/lis/Learner/NonCreditLearner"
        Learner_GuestLearner = "urn:lti:role:ims/lis/Learner/GuestLearner"
        Learner_ExternalLearner = "urn:lti:role:ims/lis/Learner/ExternalLearner"
        Learner_Instructor = "urn:lti:role:ims/lis/Learner/Instructor"
        Instructor = "urn:lti:role:ims/lis/Instructor"
        Instructor_PrimaryInstructor = "urn:lti:role:ims/lis/Instructor/PrimaryInstructor"
        Instructor_Lecturer = "urn:lti:role:ims/lis/Instructor/Lecturer"
        Instructor_GuestInstructor = "urn:lti:role:ims/lis/Instructor/GuestInstructor"
        Instructor_ExternalInstructor = "urn:lti:role:ims/lis/Instructor/ExternalInstructor"
        ContentDeveloper = "urn:lti:role:ims/lis/ContentDeveloper"
        ContentDeveloper_ContentDeveloper = "urn:lti:role:ims/lis/ContentDeveloper/ContentDeveloper"
        ContentDeveloper_Librarian = "urn:lti:role:ims/lis/ContentDeveloper/Librarian"
        ContentDeveloper_ContentExpert = "urn:lti:role:ims/lis/ContentDeveloper/ContentExpert"
        ContentDeveloper_ExternalContentExpert = "urn:lti:role:ims/lis/ContentDeveloper/ExternalContentExpert"
        Member = "urn:lti:role:ims/lis/Member"
        Member_Member = "urn:lti:role:ims/lis/Member/Member"
        Manager = "urn:lti:role:ims/lis/Manager"
        Manager_AreaManager = "urn:lti:role:ims/lis/Manager/AreaManager"
        Manager_CourseCoordinator = "urn:lti:role:ims/lis/Manager/CourseCoordinator"
        Manager_Observer = "urn:lti:role:ims/lis/Manager/Observer"
        Manager_ExternalObserver = "urn:lti:role:ims/lis/Manager/ExternalObserver"
        Mentor = "urn:lti:role:ims/lis/Mentor"
        Mentor_Mentor = "urn:lti:role:ims/lis/Mentor/Mentor"
        Mentor_Reviewer = "urn:lti:role:ims/lis/Mentor/Reviewer"
        Mentor_Advisor = "urn:lti:role:ims/lis/Mentor/Advisor"
        Mentor_Auditor = "urn:lti:role:ims/lis/Mentor/Auditor"
        Mentor_Tutor = "urn:lti:role:ims/lis/Mentor/Tutor"
        Mentor_LearningFacilitator = "urn:lti:role:ims/lis/Mentor/LearningFacilitator"
        Mentor_ExternalMentor = "urn:lti:role:ims/lis/Mentor/ExternalMentor"
        Mentor_ExternalReviewer = "urn:lti:role:ims/lis/Mentor/ExternalReviewer"
        Mentor_ExternalAdvisor = "urn:lti:role:ims/lis/Mentor/ExternalAdvisor"
        Mentor_ExternalAuditor = "urn:lti:role:ims/lis/Mentor/ExternalAuditor"
        Mentor_ExternalTutor = "urn:lti:role:ims/lis/Mentor/ExternalTutor"
        Mentor_ExternalLearningFacilitator = "urn:lti:role:ims/lis/Mentor/ExternalLearningFacilitator"
        Administrator = "urn:lti:role:ims/lis/Administrator"
        Administrator_Administrator = "urn:lti:role:ims/lis/Administrator/Administrator"
        Administrator_Support = "urn:lti:role:ims/lis/Administrator/Support"
        Administrator_Developer = "urn:lti:role:ims/lis/Administrator/Developer"
        Administrator_SystemAdministrator = "urn:lti:role:ims/lis/Administrator/SystemAdministrator"
        Administrator_ExternalSystemAdministrator = "urn:lti:role:ims/lis/Administrator/ExternalSystemAdministrator"
        Administrator_ExternalDeveloper = "urn:lti:role:ims/lis/Administrator/ExternalDeveloper"
        Administrator_ExternalSupport = "urn:lti:role:ims/lis/Administrator/ExternalSupport"
        TeachingAssistant = "urn:lti:role:ims/lis/TeachingAssistant"
        TeachingAssistant_TeachingAssistant = "urn:lti:role:ims/lis/TeachingAssistant/TeachingAssistant"
        TeachingAssistant_TeachingAssistantSection = "urn:lti:role:ims/lis/TeachingAssistant/TeachingAssistantSection"
        TeachingAssistant_TeachingAssistantSectionAssociation = "urn:lti:role:ims/lis/TeachingAssistant/TeachingAssistantSectionAssociation"
        TeachingAssistant_TeachingAssistantOffering = "urn:lti:role:ims/lis/TeachingAssistant/TeachingAssistantOffering"
        TeachingAssistant_TeachingAssistantTemplate = "urn:lti:role:ims/lis/TeachingAssistant/TeachingAssistantTemplate"
        TeachingAssistant_TeachingAssistantGroup = "urn:lti:role:ims/lis/TeachingAssistant/TeachingAssistantGroup"
        TeachingAssistant_Grader = "urn:lti:role:ims/lis/TeachingAssistant/Grader"
      end
    end
  end
end
